@prefix sps:  <http://www.labd.org/2015/sport/schema#> 
@prefix hms:  <http://www.inria.fr/2007/09/11/humans.rdfs#> 
@prefix spi: <http://www.labd.org/2015/sport/instance#>
SELECT  ?z ?x
WHERE 
{ 
	spi:Basket sps:match ?list
	?list sps:duree ?y
	?list rdfs:label ?z
	?y rdfs:member ?x
	FILTER (REGEX(STR(?x), "NBA"))
}