@prefix sps:  <http://www.labd.org/2015/sport/schema#> 
@prefix hms:  <http://www.inria.fr/2007/09/11/humans.rdfs#> 
@prefix spi: <http://www.labd.org/2015/sport/instance#>
SELECT ?x
WHERE {
	?x sps:pratique ?y
	?x sps:pratique ?z
	FILTER (?y < ?z)
}